# Generated by Django 2.0 on 2017-12-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mesage',
            new_name='message',
        ),
    ]
